# GeminiCraftChat 配置文件

# API 设置
api:
  model: "gemini-pro"  # 模型名称
  key: "your-api-key-here"  # API密钥（建议使用环境变量 GEMINI_API_KEY）
  timeout: 30  # 请求超时时间（秒）
  max_retries: 3  # 最大重试次数
  retry_delay: 1000  # 重试间隔（毫秒）
  # 中转API设置
  proxy:
    enabled: false  # 是否启用中转API
    url: "http://your-proxy-api.com/v1/chat"  # 中转API地址
    method: "POST"  # 请求方法
    headers:  # 自定义请求头
      Authorization: "Bearer ${PROXY_API_KEY}"  # 支持环境变量
      Content-Type: "application/json"
    request_format:  # 请求体格式
      model: "${model}"  # 使用配置中的model值
      messages: "${messages}"  # 消息内容
      temperature: "${temperature}"  # 使用配置中的temperature值
    response_format:  # 响应体格式
      content_path: "choices[0].message.content"  # 响应内容的JSON路径
      error_path: "error.message"  # 错误信息的JSON路径
  rate_limit:
    max_requests: 60  # 每分钟最大请求数
    cooldown: 1000  # 请求间隔（毫秒）
  generation:
    temperature: 0.7  # 生成温度 (0.0-1.0)，越高越有创意，越低越稳定
    top_k: 40  # 取前K个最可能的词
    top_p: 0.95  # 取概率和为P的词
    max_output_tokens: 1024  # 最大输出长度

# 聊天设置
chat:
  trigger: "ai"  # 默认触发词
  cooldown: 10000  # 消息冷却时间（毫秒）
  max_history: 10  # 每个玩家保存的最大历史消息数
  max_length: 500  # 最大消息长度
  # 是否启用独立对话
  independent_chat: true
  # 消息格式
  format:
    thinking: "§7[AI] §f正在思考中..."
    response: "§7[AI] §f%s"
    error: "§c[AI] 发生错误：%s"
  commands:
    switch_persona: "切换人设"
    set_persona: "设置人设"
    change_model: "切换模型"
    clear_history: "清除历史"
    clear_all_history: "清除所有历史记录"  # 管理员命令

# 伪人系统设置
npc:
  # 触发概率 (0-100)
  trigger_chance: 15
  # 是否启用记忆系统
  enable_memory: true
  # 最大记忆消息数
  max_memory: 20
  # 伪人列表
  list:
    alice:
      name: "爱丽丝"
      description: "一个活泼可爱的女孩"
      personality: "你是一个名叫爱丽丝的16岁女孩，性格活泼开朗，说话方式可爱俏皮。你喜欢用可爱的语气和表情符号交谈。"
      trigger_words: ["你好", "早上好", "晚上好"]
    bob:
      name: "鲍勃"
      description: "一个严肃的管理员"
      personality: "你是一个名叫鲍勃的服务器管理员，性格严谨认真。你说话方式正式，总是以帮助他人为己任。"
      trigger_words: ["帮助", "规则", "问题"]

# 权限设置
permissions:
  use: "gcc.use"
  admin: "gcc.admin"
  persona:
    create: "gcc.persona.create"
    edit: "gcc.persona.edit"
    delete: "gcc.persona.delete"
  bypass_cooldown: "gcc.bypass_cooldown"
  npc:
    manage: "gcc.npc.manage"
    create: "gcc.npc.create"
    edit: "gcc.npc.edit"
    delete: "gcc.npc.delete"

# 人设列表
personas:
  default:
    name: "默认助手"
    description: "一个友好的AI助手"
    context: "你是一个友好的AI助手，会用简单易懂的方式回答问题。"

# 敏感词设置
word_filter:
  enabled: true  # 是否启用敏感词过滤
  words: []  # 敏感词列表
  replacement: "***"  # 替换字符

# 调试设置
debug:
  # 总开关
  enabled: false
  # 日志设置
  log_api_calls: false  # 记录API调用
  log_chat_history: false  # 记录聊天历史
  log_level: INFO  # 日志级别：DEBUG, INFO, WARNING, ERROR
  # 日志文件设置
  file:
    max_size: 10  # 单个日志文件最大大小（MB）
    max_history: 7  # 保留的历史日志文件天数
    compress: true  # 是否压缩历史日志
  # 性能监控
  performance:
    log_slow_api_calls: true  # 记录慢API调用
    slow_api_threshold: 1000  # 慢API调用阈值（毫秒）
    log_memory_usage: false  # 记录内存使用情况
    memory_check_interval: 300  # 内存检查间隔（秒）
  # 错误追踪
  error_tracking:
    log_stack_trace: true  # 记录完整堆栈跟踪
    log_error_context: true  # 记录错误发生时的上下文
    notify_admin: true  # 错误发生时通知管理员
  # 开发者选项
  developer:
    log_config_changes: true  # 记录配置文件变更
    log_command_execution: true  # 记录命令执行
    log_permission_checks: false  # 记录权限检查 