name: GeminiCraftChat
version: '${project.version}'
main: cn.ningmo.geminicraftchat.GeminiCraftChat
api-version: '1.20'
author: NingmoDev
description: 一个基于 Gemini API 的 Minecraft 聊天 AI 插件

commands:
  gcc:
    description: GeminiCraftChat 主命令
    usage: /gcc help
    aliases: [geminicraftchat, 人工智能, ai, 聊天]
  gcreload:
    description: 重新加载 GeminiCraftChat 配置
    usage: /gcreload
    aliases: [重载ai, 重载人工智能]
    permission: gcc.admin

permissions:
  gcc.use:
    description: 允许使用基本聊天功能
    default: true
  gcc.admin:
    description: 允许使用管理员命令
    default: op
    children:
      gcc.use: true
  gcc.persona.create:
    description: 允许创建人设
    default: op
  gcc.persona.edit:
    description: 允许编辑人设
    default: op
  gcc.persona.delete:
    description: 允许删除人设
    default: op
  gcc.bypass_cooldown:
    description: 允许绕过聊天冷却
    default: op
  gcc.npc.manage:
    description: 允许管理NPC
    default: op
  gcc.npc.create:
    description: 允许创建NPC
    default: op
  gcc.npc.edit:
    description: 允许编辑NPC
    default: op
  gcc.npc.delete:
    description: 允许删除NPC
    default: op 